title: Mecha Cultivation
author: GitHub User
email: lou.shen07@din.com
description: > # this means to ignore newlines until "baseurl:"
  Technological advancements, AI are all 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
